import simpy
import World as w
from Perception import Event as e
from Platform import Platform as plat, PlatformTask as platTask

"""create simulation objects"""
env = simpy.Environment()
simpleWorld = w.World(6,7.5,env)
simpleTask1 = platTask.PlatformTask('A1')
simpleTask2 = platTask.PlatformTask('A11')
platform1 = plat.Platform('platform 1',env,simpleWorld)
platform2 = plat.Platform('platform 2',env,simpleWorld)

"""1.create world model(s)"""
platform1.WM.createArea(6, 7.5, 0, 'A')
platform1.WM.createArea(1.5, 1.5, 1, 'A1')
platform1.WM.createArea(1.5, 1.5, 1, 'A2')
platform1.WM.createArea(1.5, 1.5, 1, 'A3')
platform1.WM.createArea(1.5, 1.5, 1, 'A4')
platform1.WM.createArea(1.5, 1.5, 1, 'A5')
platform1.WM.createArea(1.5, 1.5, 1, 'A6')
platform1.WM.createArea(1.5, 3, 1, 'A7')
platform1.WM.createArea(1.5, 3, 1, 'A8')
platform1.WM.createArea(1.5, 3, 1, 'A9')
platform1.WM.createArea(1.5, 1.5, 1, 'A10')
platform1.WM.createArea(1.5, 1.5, 1, 'A11')
platform1.WM.createArea(1.5, 1.5, 1, 'A12')
platform1.WM.createArea(1.5, 1.5, 1, 'A13')


platform1.WM.containArea('A', 'A1', [-2.25, 3])
platform1.WM.containArea('A', 'A2', [2.25, 3])
platform1.WM.containArea('A', 'A3', [-2.25, 1.5])
platform1.WM.containArea('A', 'A4', [-0.75, 1.5])
platform1.WM.containArea('A', 'A5', [0.75, 1.5])
platform1.WM.containArea('A', 'A6', [2.25, 1.5])
platform1.WM.containArea('A', 'A7', [-2.25, -0.75])
platform1.WM.containArea('A', 'A8', [-0.75, -0.75])
platform1.WM.containArea('A', 'A9', [2.25, -0.75])
platform1.WM.containArea('A', 'A10', [-2.25, -3])
platform1.WM.containArea('A', 'A11', [-0.75, -3])
platform1.WM.containArea('A', 'A12', [0.75, -3])
platform1.WM.containArea('A', 'A13', [2.25, -3])

platform2.WM.createArea(6, 7.5, 0, 'A')
platform2.WM.createArea(1.5, 1.5, 1, 'A1')
platform2.WM.createArea(1.5, 1.5, 1, 'A2')
platform2.WM.createArea(1.5, 1.5, 1, 'A3')
platform2.WM.createArea(1.5, 1.5, 1, 'A4')
platform2.WM.createArea(1.5, 1.5, 1, 'A5')
platform2.WM.createArea(1.5, 1.5, 1, 'A6')
platform2.WM.createArea(1.5, 3, 1, 'A7')
platform2.WM.createArea(1.5, 3, 1, 'A8')
platform2.WM.createArea(1.5, 3, 1, 'A9')
platform2.WM.createArea(1.5, 1.5, 1, 'A10')
platform2.WM.createArea(1.5, 1.5, 1, 'A11')
platform2.WM.createArea(1.5, 1.5, 1, 'A12')
platform2.WM.createArea(1.5, 1.5, 1, 'A13')


platform2.WM.containArea('A', 'A1', [-2.25, 3])
platform2.WM.containArea('A', 'A2', [2.25, 3])
platform2.WM.containArea('A', 'A3', [-2.25, 1.5])
platform2.WM.containArea('A', 'A4', [-0.75, 1.5])
platform2.WM.containArea('A', 'A5', [0.75, 1.5])
platform2.WM.containArea('A', 'A6', [2.25, 1.5])
platform2.WM.containArea('A', 'A7', [-2.25, -0.75])
platform2.WM.containArea('A', 'A8', [-0.75, -0.75])
platform2.WM.containArea('A', 'A9', [2.25, -0.75])
platform2.WM.containArea('A', 'A10', [-2.25, -3])
platform2.WM.containArea('A', 'A11', [-0.75, -3])
platform2.WM.containArea('A', 'A12', [0.75, -3])
platform2.WM.containArea('A', 'A13', [2.25, -3])

platform1.WM.setStartingArea('A2')
platform2.WM.setStartingArea('A13')
simpleWorld.setAreaList(platform1.WM.areaList)
simpleWorld.setAreaList(platform2.WM.areaList)

"""2. give tasks"""
platform1.giveTask(simpleTask1)
platform2.giveTask(simpleTask2)

"""3. generate paths"""

"""4. generate plans"""


platform1.plan.addState('start',None,None)
platform1.plan.addState('PS1','waiting in', 'A2')
platform1.plan.addState('PS2', 'going to', 'A6')
platform1.plan.addState('PS3', 'waiting in','A6')
platform1.plan.addState('PS4', 'going to', 'A5')
platform1.plan.addState('PS5', 'waiting in','A5')
platform1.plan.addState('PS6', 'going to', 'A4')
platform1.plan.addState('PS7', 'waiting in','A4')
platform1.plan.addState('PS8', 'going to', 'A3')
platform1.plan.addState('PS9', 'waiting in','A3')
platform1.plan.addState('PS10', 'going to', 'A7')
platform1.plan.addState('PS11', 'waiting in','A7')
platform1.plan.addState('PS12', 'going to', 'A10')
platform1.plan.addState('PS13', 'waiting in','A10')
platform1.plan.currentStateLabel = 'start'

platform1.plan.addTrigger('start trigger','start','PS1',[[e.Event('location',platform1.WM.currentArea.label,platform1.label)]])
platform1.plan.addTrigger('PT1','PS1','PS2',[[e.Event('area','A6','available')]])
platform1.plan.addTrigger('PT2', 'PS2', 'PS1', [[e.Event('area', 'A6', 'unavailable')],[e.Event('location','A2',platform1.label)]])
platform1.plan.addTrigger('PT3', 'PS2', 'PS3',[[e.Event('location', 'A6', platform1.label)]])
platform1.plan.addTrigger('PT4','PS3','PS4',[[e.Event('area','A5','available')]])
platform1.plan.addTrigger('PT5', 'PS4', 'PS3', [[e.Event('area', 'A5', 'unavailable')],[e.Event('location','A6',platform1.label)]])
platform1.plan.addTrigger('PT6', 'PS4', 'PS5',[[e.Event('location', 'A5', platform1.label)]])
platform1.plan.addTrigger('PT7','PS5','PS6',[[e.Event('area','A4','available')]])
platform1.plan.addTrigger('PT8', 'PS6', 'PS5', [[e.Event('area', 'A4', 'unavailable')],[e.Event('location','A5',platform1.label)]])
platform1.plan.addTrigger('PT9', 'PS6', 'PS7',[[e.Event('location', 'A4', platform1.label)]])
platform1.plan.addTrigger('PT10','PS7','PS8',[[e.Event('area','A3','available')]])
platform1.plan.addTrigger('PT11', 'PS8', 'PS7', [[e.Event('area', 'A3', 'unavailable')],[e.Event('location','A4',platform1.label)]])
platform1.plan.addTrigger('PT12', 'PS8', 'PS9',[[e.Event('location', 'A3', platform1.label)]])
platform1.plan.addTrigger('PT13','PS9','PS10',[[e.Event('area','A7','available')]])
platform1.plan.addTrigger('PT14', 'PS10', 'PS9', [[e.Event('area', 'A7', 'unavailable')],[e.Event('location','A3',platform1.label)]])
platform1.plan.addTrigger('PT15', 'PS10', 'PS11',[[e.Event('location', 'A7', platform1.label)]])
platform1.plan.addTrigger('PT16','PS11','PS12',[[e.Event('area','A10','available')]])
platform1.plan.addTrigger('PT17', 'PS12', 'PS11', [[e.Event('area', 'A10', 'unavailable')],[e.Event('location','A7',platform1.label)]])
platform1.plan.addTrigger('PT18', 'PS12', 'PS3',[[e.Event('location', 'A10', platform1.label)]])


platform2.plan.addState('start',None,None)
platform2.plan.addState('PS1','waiting in', 'A13')
platform2.plan.addState('PS2', 'going to', 'A12')
platform2.plan.addState('PS3', 'waiting in','A12')
platform2.plan.addState('PS4', 'going to', 'A11')
platform2.plan.addState('PS5', 'waiting in','A11')
platform2.plan.addState('PS6', 'going to', 'A8')
platform2.plan.addState('PS7', 'waiting in','A8')
platform2.plan.addState('PS8', 'going to', 'A4')
platform2.plan.addState('PS9', 'waiting in','A4')
platform2.plan.addState('PS10', 'going to', 'A3')
platform2.plan.addState('PS11', 'waiting in','A3')
platform2.plan.addState('PS12', 'going to', 'A1')
platform2.plan.addState('PS13', 'waiting in','A1')

platform2.plan.addState('PS14', 'going to', 'A9')
platform2.plan.addState('PS15', 'waiting in','A9')
platform2.plan.addState('PS16', 'going to', 'A6')
platform2.plan.addState('PS17', 'waiting in','A6')
platform2.plan.addState('PS18', 'going to', 'A5')
platform2.plan.addState('PS19', 'waiting in','A5')
platform2.plan.currentStateLabel = 'start'

platform2.plan.addTrigger('start trigger','start','PS1',[[e.Event('location',platform2.WM.currentArea.label,platform2.label)]])
platform2.plan.addTrigger('PT1','PS1','PS2',[[e.Event('area','A12','available')]])
platform2.plan.addTrigger('PT2', 'PS2', 'PS1', [[e.Event('area', 'A12', 'unavailable')],[e.Event('location','A13',platform2.label)]])
platform2.plan.addTrigger('PT3', 'PS2', 'PS3',[[e.Event('location', 'A12', platform2.label)]])
platform2.plan.addTrigger('PT4','PS3','PS4',[[e.Event('area','A11','available')]])
platform2.plan.addTrigger('PT5', 'PS4', 'PS3', [[e.Event('area', 'A11', 'unavailable')],[e.Event('location','A12',platform2.label)]])
platform2.plan.addTrigger('PT6', 'PS4', 'PS5',[[e.Event('location', 'A11', platform2.label)]])
platform2.plan.addTrigger('PT7','PS5','PS6',[[e.Event('area','A8','available')]])
platform2.plan.addTrigger('PT8', 'PS6', 'PS5', [[e.Event('area', 'A8', 'unavailable')],[e.Event('location','A11',platform2.label)]])
platform2.plan.addTrigger('PT9', 'PS6', 'PS7',[[e.Event('location', 'A8', platform2.label)]])
platform2.plan.addTrigger('PT10','PS7','PS8',[[e.Event('area','A4','available')]])
platform2.plan.addTrigger('PT11', 'PS8', 'PS7', [[e.Event('area', 'A4', 'unavailable')],[e.Event('location','A8',platform2.label)]])
platform2.plan.addTrigger('PT12', 'PS8', 'PS9',[[e.Event('location', 'A4', platform2.label)]])
platform2.plan.addTrigger('PT13','PS9','PS10',[[e.Event('area','A3','available')]])
platform2.plan.addTrigger('PT14', 'PS10', 'PS9', [[e.Event('area', 'A3', 'unavailable')],[e.Event('location','A4',platform2.label)]])
platform2.plan.addTrigger('PT15', 'PS10', 'PS11',[[e.Event('location', 'A3', platform2.label)]])
platform2.plan.addTrigger('PT16','PS11','PS12',[[e.Event('area','A1','available')]])
platform2.plan.addTrigger('PT17', 'PS12', 'PS11', [[e.Event('area', 'A1', 'unavailable')],[e.Event('location','A3',platform2.label)]])
platform2.plan.addTrigger('PT18', 'PS12', 'PS13',[[e.Event('location', 'A1', platform2.label)]])

platform2.plan.addTrigger('PT19','PS1','PS14',[[e.Event('area','A9','available')],[e.Event('area', 'A12', 'unavailable')]])
platform2.plan.addTrigger('PT20', 'PS14', 'PS1', [[e.Event('area', 'A9', 'unavailable')],[e.Event('location','A13',platform2.label)]])
platform2.plan.addTrigger('PT21', 'PS14', 'PS15',[[e.Event('location', 'A9', platform2.label)]])
platform2.plan.addTrigger('PT22','PS15','PS16',[[e.Event('area','A6','available')]])
platform2.plan.addTrigger('PT23', 'PS16', 'PS15', [[e.Event('area', 'A6', 'unavailable')],[e.Event('location','A9',platform2.label)]])
platform2.plan.addTrigger('PT24', 'PS16', 'PS17',[[e.Event('location', 'A6', platform2.label)]])
platform2.plan.addTrigger('PT25','PS17','PS18',[[e.Event('area','A5','available')]])
platform2.plan.addTrigger('PT26', 'PS18', 'PS17', [[e.Event('area', 'A5', 'unavailable')],[e.Event('location','A6',platform2.label)]])
platform2.plan.addTrigger('PT27', 'PS18', 'PS19',[[e.Event('location', 'A5', platform2.label)]])
platform2.plan.addTrigger('PT28','PS19','PS8',[[e.Event('area','A4','available')]])
platform2.plan.addTrigger('PT29', 'PS8', 'PS19', [[e.Event('area', 'A4', 'unavailable')],[e.Event('location','A5',platform2.label)]])
platform2.plan.addTrigger('PT30', 'PS19', 'PS10',[[e.Event('location', 'A4', platform2.label)]])

"""5.create platform units"""
platform1.createUnit('platform 1 unit 1',6,0.2,[0,0])
platform2.createUnit('platform 2 unit 1',6,0.2,[0,-0.2])

"""6. add objects and structures"""
simpleWorld.addStructure(6,7.5,[0,0])
simpleWorld.addStructure(3,1.5,[0,3])
simpleWorld.addStructure(1.5,3,[0.75,-0.75])
simpleWorld.addObject(0.5,[0.75,-3])
#simpleWorld.addObject(0.5,[2.25,-1.5])
#simpleWorld.addObject(0.5,[2.25,1.5])

"""run simulation. one time unit is 0.01 seconds"""
env.run(2000)